services:
  postgres:
    image: postgres:16.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - private

  redis:
    image: redis/redis-stack:latest
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - private
    volumes:
      - redis_data:/var/lib/redis/data

  bun-express-api:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - private
    env_file:
      - ./.env
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
      redis:
        condition: service_healthy
        restart: true

volumes:
  postgres_data:
  redis_data:

networks:
  private:
