services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.env
    depends_on:
      - redis
      - postgres
    deploy:
      mode: replicated
      replicas: 2
    networks:
      - private

  postgres:
    image: postgres:16.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - private

  redis:
    image: redis/redis-stack:latest
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - private
    volumes:
      - redis_data:/var/lib/redis/data

  nginx:
    image: registry.docker.ir/nginx:stable-alpine3.20-perl
    ports:
      - 80:80
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - private

volumes:
  postgres_data:
  redis_data:

networks:
  private:
